--DROP SEQUENCE TESTUSER.IDSEQ;
CREATE SEQUENCE TESTUSER.IDSEQ
INCREMENT BY 1
START WITH 1
MAXVALUE 9999;
--DROP TABLE MEMBER;
create table member
(
 id number DEFAULT IDSEQ.NEXTVAL,
 name varchar(255),
 primary key (id)
);

